US14 Listagem de Línguas por troncos linguísticos #101
fga-eps-mds/2021.1-Multilind-content-server pull request #14
Opened 2021-09-26 18:19 UTC by CarlosZoft

## Description 

In this PR, CRUD and trunk tests with refactoring have been added

## Solve (Issues)

#101

## Tasks done with this PR
* [x] CRUD Tronco 
* [x] Tests Tronco

## Prints
### Testes :
![Screenshot from 2021-09-26 15-08-14](https://user-images.githubusercontent.com/62192072/134819222-0ee793d3-e035-4c0d-8f0f-d99bfc3f585d.png)
### Create :
![Screenshot from 2021-09-26 15-11-34](https://user-images.githubusercontent.com/62192072/134819297-94b9b637-cd5d-4f19-ae1e-e4752e130006.png)

### Read :
![Screenshot from 2021-09-26 15-13-46](https://user-images.githubusercontent.com/62192072/134819365-41168c32-c2fd-455c-84a6-83f29c076f36.png)

### Update :
![Screenshot from 2021-09-26 15-15-30](https://user-images.githubusercontent.com/62192072/134819420-b20c709e-2297-49df-9688-bb48ad25a111.png)

### Delete :
![Screenshot from 2021-09-26 15-18-07](https://user-images.githubusercontent.com/62192072/134819479-6761595f-1822-49cc-8193-6adb12c19455.png)
![Screenshot from 2021-09-26 15-19-05](https://user-images.githubusercontent.com/62192072/134819508-41dd5101-0ebf-455d-ae0a-2dc6139324ad.png)

2021-09-28 00:03 UTC, sofiapatrocinio commented
Só arrumar os conflitos :)

2021-09-28 19:28 UTC, micaellagouveia commented
Branch está com conflitos.

2021-09-30 14:59 UTC, micaellagouveia approved these changes

2021-10-02 01:39 UTC, pedroeagle requested changes

2021-10-02 01:39 UTC, pedroeagle commented on src/database/migrations/20210905150640-createTable-Lingua.js
> +          onUpdate: "SET NULL",
por que onUpdate e onDelete SET NULL?

2021-10-03 17:35 UTC, pedroeagle approved these changes

2021-10-03 17:52 UTC, merged