CRUD de Etnias e testes unitários
fga-eps-mds/2021.1-Multilind-content-server pull request #2
Opened 2021-09-11 03:08 UTC by CarlosZoft

## Description 
Neste PR foi adicionado o CRUD de etnias e teste unitário dos métodos.

2021-09-11 11:51 UTC, micaellagouveia approved these changes

2021-09-11 13:33 UTC, pedroeagle requested changes
@CarlosZoft Exporta um arquivo do insomnia e sobe no diretório insomnia na raiz do projeto com as requisições possíveis. Isso vai ser útil pra quem for testar e evoluir futuramente.

2021-09-11 13:36 UTC, pedroeagle requested changes
Remove os arquivos yarn.lock.json e, package-lock.json eles não precisam ser subidos. Recomendo colocar no .gitignore também.

2021-09-12 16:43 UTC, pedroeagle approved these changes
Muito bom! 🎉

2021-09-12 16:44 UTC, merged